# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
rrepo: https://github.com/ambv/black
    rev: 21.10b0
    hooks:
    - id: black
      language: python
      types: [python]
      args: ["--line-length=120"]
