[tool.poetry]
name = "ipumspy"
version = "0.1.0"
description = "A collection of tools for working with IPUMS data"
authors = ["Kevin Wilson"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0.4"
click = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
black = "^19.10b0"

[tool.poetry.scripts]
ipums = "ipumspy.cli:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
